language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

install:
  - composer self-update
  - composer install --no-interaction

script:
  - phpunit --bootstrap vendor/autoload.php
